version: "3"
services:
    db_postgres:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        volumes:
            - dbdata:/var/lib/postgresql/data
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - POSTGRES_DB=docker
            - POSTGRES_HOST_AUTH_METHOD=password
    adminer:
        image: adminer
        restart: always
        ports:
        - 8080:8080
volumes:
    dbdata:
